### ISSUE TITLE
404 Not Found @1.14.0

### ISSUE THREAD

**Issue by Mcbeer** [ljharb/es-abstract#57] opened 2019-09-30 08:14 UTC
When trying to download 1.14.0 via Bitbucket Pipelines, i get the following error.
The app i run is built with Create-React-App and i suspect this is a dependency of that. This breaks building via pipelines for now.

```
npm ERR! 404  'es-abstract@1.14.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by ljharb** [comment] 2019-09-30 11:06
v1.14.1 is out, and v1.14.0 is unpublished.

The window where v1.14.0 was out was very brief; you perhaps need to update your lockfile?

Duplicate of #55.

**Closed by ljharb** 2019-09-30 11:06 UTC
