### ISSUE TITLE
version around 1.18 breaking CI?

### ISSUE THREAD

**Issue by lemoustachiste** [ljharb/es-abstract#132] opened 2021-07-19 12:29 UTC
Hi,

I wasn't able to pinpoint exactly which version breaks CI (with Travis), but reverting a change of this package from 1.18.3 to 1.17.2 fixed my issue.

This was the output before the change:
```
$ npm ci 

npm ERR! string.prototype.trimend not accessible from es-abstract
```

Now my build runs as expected. It looks similar to this one: https://github.com/microsoft/azure-pipelines-tasks/issues/14725

**Comment by ljharb** [comment] 2021-07-19 15:17
Are you perhaps using “not npm”? That error message implies yarn 2 or pnpm.

**Comment by ljharb** [comment] 2021-07-19 15:17
Also, can you figure out the exact version where this started happening?

**Comment by zinyosrim** [comment] 2021-07-21 14:36
I deinstalled node.
Reinstalled and now have v14.15.3
I upgraded npm to 7.20.0
Installed es-abstract@1.17.2

The issue is still there when I try to deploy
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/17767575/126506927-e3c5996a-61ad-4ef4-8715-fc7596841eb7.png">

**Comment by ljharb** [comment] 2021-07-21 15:33
Does it also happen on npm 6, or only on npm 7?

**Comment by zinyosrim** [comment] 2021-07-21 15:43
Just tried with V.6. Same issue


Jordan Harband ***@***.***> schrieb am Mi. 21. Juli 2021 um
17:33:

**Comment by ljharb** [comment] 2021-07-21 15:47
Is there anything in `~/.npmrc` or `.npmrc` besides auth/registry stuff? anything in `env | grep -i npm`?

**Comment by isaacs** [comment] 2021-07-21 17:57
That "not accessible from" error only exists in npm v6.  It comes from the `npm-logical-tree` package.  You are using npm v6 in the screenshot.  Do you get the same error in npm v7?

The error indicates that you have a package in your tree with a dependency that is not being met.  Do you see any errors when you run `npm ls`?

**Comment by ljharb** [comment] 2021-07-21 20:52
@zinyosrim to be specific, try npm 7 *in heroku*, not just locally.

**Comment by ljharb** [comment] 2021-07-22 17:31
Given that this issue only happens in npm 6 and below, and given that very few people have reported it, and given that I can't reproduce it nor do I know what action I could take in es-abstract to fix it - I'm going to close this.

However, if it becomes reproducible for me, or, if someone can come up with something i can change in this package that fixes the problem, I'll be happy to reopen it.

**Closed by ljharb** 2021-07-22 17:31 UTC

**Comment by zinyosrim** [comment] 2021-07-23 07:24
> Is there anything in `~/.npmrc` or `.npmrc` besides auth/registry stuff? anything in `env | grep -i npm`?

no
![image](https://user-images.githubusercontent.com/17767575/126749756-95b58853-74d9-44b9-9a9e-cfca9ea964fd.png)

**Comment by zinyosrim** [comment] 2021-07-23 09:12
After upgrading NPM to latest my deploy succeeded
