### ISSUE TITLE
es-abstract@1.14.0' is not in the npm registry

### ISSUE THREAD

**Issue by cesine** [ljharb/es-abstract#126] opened 2021-01-26 14:17 UTC
We are using an old version of this package which was once published, but has since gone missing in npm: 

```
npm ERR! 404  'es-abstract@1.14.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'carbon_web'
```

We can see that 1.14.0 is gone: 

https://www.npmjs.com/package/es-abstract

![Screen Shot 2021-01-26 at 9 15 13 AM](https://user-images.githubusercontent.com/196199/105856306-19b6db00-5fb7-11eb-95d0-28400a9b88c8.png)

But it does exist in this repo:

https://github.com/ljharb/es-abstract/releases/tag/v1.14.0

![Screen Shot 2021-01-26 at 9 15 40 AM](https://user-images.githubusercontent.com/196199/105856297-158abd80-5fb7-11eb-84d9-9153429f1045.png)

Are you able to republish that old version, in case we are not the only ones that find it has gone missing in npm?

**Comment by ljharb** [comment] 2021-01-26 14:36
No, i unpublished it, which means it can never be published or used again.

however, nothing should ever have depended on it without using `^`, so you should easily be able to update to the latest version.

Duplicate of #76. Duplicate of #65. Duplicate of #60. Duplicate of #58. Duplicate of #57. Duplicate of #56. Duplicate of #55. Duplicate of #73.

**Closed by ljharb** 2021-01-26 14:36 UTC
