### ISSUE TITLE
Classes are callable

### ISSUE THREAD

**Issue by zloirock** [ljharb/es-abstract#139] opened 2021-09-14 14:13 UTC
```js
require('es-abstract/2020/iscallable')(class{}) // => false
```
![image](https://user-images.githubusercontent.com/2213682/133273733-641499d2-77a1-4344-9bdd-fa1a7a13556b.png)
![image](https://user-images.githubusercontent.com/2213682/133273946-e114d1ad-f635-4689-9043-4b9cecb4d85e.png)

**Comment by zloirock** [comment] 2021-09-14 14:26
It seems a duplicate of #48 and #93, but any actions are missed for some years.

**Comment by ljharb** [comment] 2021-09-14 15:44
It is indeed a duplicate of both; no action will likely be taken for some decades, given that the real problem is the specification - class constructors are not actually callable, they just implement this with a [[Call]] slow that throws a type error. There’s no use case whatsoever for IsCallable returning true here just to throw later (since IsCallable checks basically always guard a Call).

Filing a redundant issue won’t get things moving any more than a comment on the actual issue would, fwiw.

**Closed by ljharb** 2021-09-14 15:44 UTC

**Comment by zloirock** [comment] 2021-09-14 15:53
In this case, positioning on `es-abstract` as a proper set of spec ECMAScrpt abstract operations makes no sense.

**Comment by ljharb** [comment] 2021-09-14 16:20
This isn't a productive argument. es-abstract is ES AOs for use in polyfills. If you can find a bug in a polyfill caused by IsCallable returning false for a class constructor, I'd be happy to fix it, but if it's just changing when an error is called (because class constructors aren't callable) then it's perfectly reasonable to make choices to deviate from the spec for practicality.

**Comment by zloirock** [comment] 2021-09-14 16:31
> This isn't a productive argument.

This **is** a productive argument. Even `typeof something === 'function'` is a proper `IsCallable` check for modern engines. Sure, some old engines have some minor issues (like FF2 callable regexes - but they are callable). But `es-abstract/2020/iscallable` returns `false` for classes. By the spec, classes should be callable and in too many cases in the spec `[[Construct]]` checked only when `[[Call]]` existent - so classes will not pass this check when they should., so this helper should never be used as an equal of abstract ES `IsCallable` operation.

**Comment by zloirock** [comment] 2021-09-14 16:38
The behavior of classes:
```js
function C() {
  if (!new.target) throw TypeError();
}
```
But it does not remove this `[[Call]]` from this function.

**Comment by ljharb** [comment] 2021-09-14 16:40
Yes, I'm aware - and your C function there is *effectively* not callable, so it's most useful if an "is callable" check returns false for it. In that case, of course, it's not practically possible to do so, but that doesn't mean there's no value in doing so for `class`es.

**Comment by zloirock** [comment] 2021-09-14 16:46
`IsCallable` should check is this function callable by the spec, not *effectively* - otherwise, it's not an ECMAScript abstract operation.

**Comment by ljharb** [comment] 2021-09-14 16:49
Thanks, your opinion is noted, and the issue is already tracked in #48.
