### ISSUE TITLE
(node:4665) [DEP0148] DeprecationWarning

### ISSUE THREAD

**Issue by ProgrammingPlanet** [ljharb/es-abstract#137] opened 2021-08-02 15:53 UTC
i'm using vue-cli 4.15 and getting this warning 

(node:4665) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./2020/" in the "exports" field module resolution of the package at /myProjects/frontend/node_modules/es-abstract/package.json.
Update this package.json to use a subpath pattern like "./2020/*".
(Use `node --trace-deprecation ...` to show where the warning was created)

kindly resolve it.

**Comment by ljharb** [comment] 2021-08-02 15:58
Update to v1.18.5. Duplicate of #133.

**Closed by ljharb** 2021-08-02 15:58 UTC
