### ISSUE TITLE
Module not found: Error: Can't resolve '../helpers/caseFolding'

### ISSUE THREAD

**Issue by gnu4cn** [ljharb/es-abstract#152] opened 2023-10-17 01:53 UTC
`...tract/helpers/isPropertyDescriptor.jsModuleNotFoundError: Module not found: Error: Can't resolve '../helpers/caseFolding' in '/home/lenny.peng/fire/node_modules/es-abstract/2016'`

```console
using description file: /home/lenny.peng/fire/node_modules/es-abstract/package.json (relative path: ./helpers/caseFolding)
      no extension
        /home/lenny.peng/fire/node_modules/es-abstract/helpers/caseFolding doesn't exist
      .ts
        /home/lenny.peng/fire/node_modules/es-abstract/helpers/caseFolding.ts doesn't exist
      .js
        /home/lenny.peng/fire/node_modules/es-abstract/helpers/caseFolding.js doesn't exist
      as directory
        /home/lenny.peng/fire/node_modules/es-abstract/helpers/caseFolding doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

I found the `caseFolding.json` under `node_modules/es-abstract/helpers`, but it still retported this error.

**Comment by ljharb** [comment] 2023-10-17 03:08
It's definitely there, so whatever nonstandard thing is printing out "using description file" is likely to blame.

**Comment by ljharb** [comment] 2023-10-26 20:15
I'm going to close this but am happy to keep discussing; it's definitely not an issue with this package.

**Closed by ljharb** 2023-10-26 20:15 UTC

**Comment by Shrikey26** [comment] 2023-11-07 17:36
Even I am facing the same issue.
When I manually change it to 

`var caseFolding = require('../helpers/caseFolding.json');`, the build is working fine.. 
Not sure why adding `.json` is fixing this

**Comment by pimterry** [comment] 2023-12-21 19:32
I ran into this too, and looked into it.

This is an issue when using any 1.22.0+ version of es-abstract with probably all webpack versions (4, 5, and probably further back) if you've specified a list of resolve extensions in your config but haven't explicitly included .json there. That's pretty common, e.g. the standard config for TypeScript in Webpack ([here](https://github.com/TypeStrong/ts-loader#configuration)) does this.

The issue is that `caseFolding.json` in this package is required in a few places as just `../helpers/caseFolding`, without specifying the extension. Node will automatically implicitly look for .json files when using `require()`, but that's not common elsewhere.

As a user, if you hit this too, you can fix it by including `.json` in [resolve.extensions](https://webpack.js.org/configuration/resolve/#resolveextensions) in your webpack config, and then it'll be found and everything should work as expected.

@ljharb As a package, the current code is not technically wrong as such for pure node usage, but it might save people some hassle with webpack if this extension was made explicit as `require('../helpers/caseFolding.json')` instead of leaving it implicit like this.

**Comment by ljharb** [comment] 2023-12-21 19:34
@pimterry can you file an issue on webpack about it? It's a bug not to include it, since it's what node does by default.

Are you saying that if I add the explicit extension, webpack will be able to resolve it regardless of configuration?

**Comment by pimterry** [comment] 2023-12-21 19:35
> Are you saying that if I add the explicit extension, webpack will be able to resolve it regardless of configuration?

Yes, exactly.

> can you file an issue on webpack about it? It's a bug not to include it, since it's what node does by default.

This isn't a webpack bug - their defaults do include it (at least, according to the docs). The problem is the vast number of individual user configs that set this for more specific values (e.g. for TypeScript) and don't include .json as well (because it's not generally required).

**Comment by ljharb** [comment] 2023-12-21 20:03
It sounds like their readme should be updated, though :-)

I'll consider adding the explicit extension.

**Comment by ljharb** [comment] 2023-12-21 21:32
The next version will include the explicit extension.

**Comment by akinnee** [comment] 2024-01-26 22:47
Solved my issue. I'm working on upgrading a legacy codebase. For some reason, after upgrading enzyme, I needed to add the extension of the file that jest-resolve couldn't find to the webpack config's `resolve.extensions` array.
