### ISSUE TITLE
version 1.14.0 missing in pakagemanager

### ISSUE THREAD

**Issue by LauLaman** [ljharb/es-abstract#60] opened 2019-10-19 08:59 UTC
At https://www.npmjs.com/package/es-abstract version 1.14.0 is missing.
All other versions seem to be there.

Since the tag is stile here in Github, is there any reason why this particular version had been removed from the package manager?

(read along @noahlvb)

**Comment by ljharb** [comment] 2019-10-19 15:28
It’s not missing, it was deliberately unpublished - after v1.14.1 was released, so semver should have automatically have updated you.

It was unpublished due to mistakenly included files in v1.14.0.

Duplicate of #58. Duplicate of #57. Duplicate of #56. Duplicate of #55.

**Closed by ljharb** 2019-10-19 15:28 UTC
