### ISSUE TITLE
Version 1.14.0 not available

### ISSUE THREAD

**Issue by tainguyenbui** [ljharb/es-abstract#73] opened 2019-11-14 09:24 UTC
**Description:**
es-abstract@1.14.0 has been removed from the package manager causing issues when downloading dependencies.

There are quite a few libraries that still depend on that version

```
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/es-abstract/-/es-abstract-1.14.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/circleci/repo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1
CircleCI received exit code 1
```

**Comment by JakeChampion** [comment] 2019-11-14 11:02
Duplicate of #65, #60, #58, #57, #56, #55

From https://github.com/ljharb/es-abstract/issues/55#issuecomment-527707767
> Indeed, i apologize for the inconvenience - it hadn’t been 24 hours yet, and it had files in it that it shouldn’t have. v1.14.1 is already published, before i unpublished v1.14.0, so it should be trivial to update it in your lockfile.

**Comment by ljharb** [comment] 2019-11-14 16:59
If you tell me which libraries explicitly depend on 1.14.0, i will happily go update them.

**Closed** 2019-11-14 16:59 UTC

**Comment by mkoo21** [comment] 2019-11-14 17:18
```
├─┬ eslint-plugin-react-app@6.0.3
│ ├─┬ eslint-plugin-import@2.18.2
│ │ ├─┬ array-includes@3.0.3
│ │ │ └── es-abstract@1.14.0
│ │ └─┬ object.values@1.1.0
│ │   └── es-abstract@1.14.0  deduped
│ └─┬ eslint-plugin-react@7.14.3
│   ├─┬ object.entries@1.1.0
│   │ └── es-abstract@1.14.0  deduped
│   └─┬ object.fromentries@2.0.0
│     └── es-abstract@1.14.0  deduped
└─┬ jest@24.9.0
  └─┬ jest-cli@24.9.0
    └─┬ realpath-native@1.1.0
      └─┬ util.promisify@1.0.0
        └─┬ object.getownpropertydescriptors@2.0.3
          └── es-abstract@1.14.0  deduped
```

**Comment by mkoo21** [comment] 2019-11-14 17:19
> If you tell me which libraries explicitly depend on 1.14.0, i will happily go update them.

Here are a few (up to date)
```
├─┬ eslint-plugin-react-app@6.0.3
│ ├─┬ eslint-plugin-import@2.18.2
│ │ ├─┬ array-includes@3.0.3
│ │ │ └── es-abstract@1.14.0
│ │ └─┬ object.values@1.1.0
│ │   └── es-abstract@1.14.0  deduped
│ └─┬ eslint-plugin-react@7.14.3
│   ├─┬ object.entries@1.1.0
│   │ └── es-abstract@1.14.0  deduped
│   └─┬ object.fromentries@2.0.0
│     └── es-abstract@1.14.0  deduped
└─┬ jest@24.9.0
  └─┬ jest-cli@24.9.0
    └─┬ realpath-native@1.1.0
      └─┬ util.promisify@1.0.0
        └─┬ object.getownpropertydescriptors@2.0.3
          └── es-abstract@1.14.0  deduped
```

**Comment by ljharb** [comment] 2019-11-14 17:33
All of those use a `^`, so the only issue is your lockfile being saved at the wrong time. The cost you assume when you add a lockfile is knowing how to update transitive deps in it.

If you force reinstall those top two packages, you should see much later versions of the transitive deps installed.

**Comment by tainguyenbui** [comment] 2019-11-14 18:53
That is correct, I solved the issue by deleting node_modules and yarn.lock

It is now all good. Thanks!
