### ISSUE TITLE
es-abstract@1.14.0 not found

### ISSUE THREAD

**Issue by Itrulia** [ljharb/es-abstract#65] opened 2019-10-30 09:41 UTC
Why has the [version 1.14.0](https://www.npmjs.com/package/es-abstract/v/1.14.0) pulled from npm? Our CI is now failing as it can not find it.

**Comment by JakeChampion** [comment] 2019-10-30 09:43
Duplicate of https://github.com/ljharb/es-abstract/issues/60, https://github.com/ljharb/es-abstract/issues/58, https://github.com/ljharb/es-abstract/issues/57, https://github.com/ljharb/es-abstract/issues/56, https://github.com/ljharb/es-abstract/issues/55

**Comment by JakeChampion** [comment] 2019-10-30 09:44
From https://github.com/ljharb/es-abstract/issues/55#issuecomment-527707767
> Indeed, i apologize for the inconvenience - it hadn’t been 24 hours yet, and it had files in it that it shouldn’t have. v1.14.1 is already published, before i unpublished v1.14.0, so it should be trivial to update it in your lockfile.

**Closed** 2019-10-30 09:49 UTC

**Comment by Itrulia** [comment] 2019-10-30 09:50
There are packages depending on it, so it is not in every case trivial.
