### ISSUE TITLE
V1.14.0 was not available on npm

### ISSUE THREAD

**Issue by kuyeduwu** [ljharb/es-abstract#56] opened 2019-09-06 11:52 UTC
The latest version on npm was v1.14.1, but seems v1.14.0 was removed from npm, the following error received if the v1.14.0 is a dependency:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for es-abstract@1.14.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by Xotic750** [comment] 2019-09-06 12:03
https://github.com/ljharb/es-abstract/issues/55

**Comment by delueg** [comment] 2019-09-06 14:06
this makes my life so hard in the moment

**Comment by ljharb** [comment] 2019-09-06 16:34
Duplicate of #55 

@delueg semver should make updating to v1.14.1 trivial.

**Closed by ljharb** 2019-09-06 16:34 UTC

**Comment by delueg** [comment] 2019-09-06 20:42
Maybe I don't get it but many dependencies of my project have es-abstract as a dependency itself. No direct dependency in my project. When ever i for example delete node_modules and run "npm i" the dependencies still fetch 1.14.0. is it really a solution to hack the package-lock.json?

**Comment by ljharb** [comment] 2019-09-06 23:16
Not to hack it; but when using a lockfile you incur the burden of explicitly maintaining new transitive dependencies. In this case, you have to use npm update to update your lockfile, or regenerate it.

**Comment by delueg** [comment] 2019-09-07 07:29
Yes you are right.. i forgot to say that I was deleting the lockfile as well. Yesterday it was still fetching 1.14.0 .. but now it works.
